#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-upstream

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 30 19 * * *

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Load upstream commits
      run:  | 
        svn co https://github.com/fw876/helloworld/trunk/luci-app-ssr-plus
        # git clone https://github.com/rufengsuixing/luci-app-adguardhome
        svn co https://github.com/Lienol/openwrt/trunk/package/diy/luci-app-adguardhome
        git clone https://github.com/garypang13/luci-theme-edge
        git clone https://github.com/jerrykuku/luci-theme-argon
        svn co https://github.com/openwrt/luci/trunk/applications/luci-app-acme
        svn co https://github.com/coolsnowwolf/packages/trunk/net/miniupnpd
        git clone https://github.com/pymumu/luci-app-smartdns -b lede
        git clone https://github.com/lisaac/luci-app-diskman
        mkdir parted && cp luci-app-diskman/Parted.Makefile parted/Makefile
        git clone https://github.com/tty228/luci-app-serverchan
        git clone https://github.com/brvphoenix/luci-app-wrtbwmon
        git clone https://github.com/brvphoenix/wrtbwmon
        git clone https://github.com/destan19/OpenAppFilter && mv -f OpenAppFilter/* ./
        svn co https://github.com/kenzok8/openwrt-packages/trunk/luci-app-advancedsetting
        git clone https://github.com/lisaac/luci-app-dockerman
        svn co https://github.com/openwrt/luci/trunk/applications/luci-app-sqm
        git clone https://github.com/garypang13/r8125
        git clone https://github.com/ElonH/Rclone-OpenWrt && mv -f Rclone-OpenWrt/* ./
        git clone https://github.com/jefferymvp/luci-app-koolproxyR
        #svn co https://github.com/chuansao-258/filters-openwrt/trunk/luci-app-koolproxyR
        #svn co https://github.com/tzxiaozhen88/luci-app-koolproxyR
        git clone https://github.com/garypang13/luci-app-qbittorrent
        git clone https://github.com/jerrykuku/luci-app-vssr
        git clone https://github.com/jerrykuku/lua-maxminddb
        git clone https://github.com/peter-tank/luci-app-dnscrypt-proxy2
        git clone https://github.com/rufengsuixing/luci-app-autoipsetadder
        git clone https://github.com/jerrykuku/node-request.git
        git clone https://github.com/jerrykuku/luci-app-jd-dailybonus
        git clone https://github.com/jerrykuku/luci-theme-argon

        svn co https://github.com/vernesong/OpenClash/branches/master/luci-app-openclash
        git clone https://github.com/frainzy1477/luci-app-clash
        svn co https://github.com/solidus1983/luci-theme-opentomato/trunk/luci/themes/luci-theme-opentomato
        svn co https://github.com/Lienol/openwrt-package/trunk/others/luci-app-syncthing
        svn co https://github.com/Lienol/openwrt-package/trunk/others/luci-app-control-timewol
        svn co https://github.com/dogbutcat/openwrt-packages/trunk/openwrt-udp2raw
        svn co https://github.com/dogbutcat/openwrt-packages/trunk/speederv2

        git clone https://github.com/garypang13/openwrt-adguardhome
        git clone https://github.com/garypang13/luci-app-eqos
        git clone https://github.com/garypang13/luci-app-amule
        # git clone https://github.com/garypang13/openwrt-qbittorrent && mv -f openwrt-qbittorrent/* ./
        git clone https://github.com/garypang13/openwrt-filerun
        git clone https://github.com/garypang13/luci-app-baidupcs-web
        svn co https://github.com/openwrt/packages/branches/openwrt-19.07/libs/libdouble-conversion
        svn co https://github.com/openwrt/openwrt/branches/openwrt-19.07/package/network/services/samba36

    - name: Apply commit changes
      run: |
        if [ -f ./.git/MERGE_MSG ]; then
        mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message
        sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message
        sed -i '/^\#.*/d' ./tmp/message
        git commit --file="./tmp/message"
        else
        echo "There is no merge commits."
        fi

    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
      run: git push origin $DOWNSTREAM_BRANCH
